package concessionaria.gui.views;

import javax.swing.JLabel;
import concessionaria.entidades.Funcionario;
import concessionaria.gui.controllers.FormularioFuncionariosController;

public class FormularioFuncionarios extends javax.swing.JPanel {
    
    private final FormularioFuncionariosController controller;
    
    private Funcionario funcionarioEditado;
    private boolean editando = false;
    
    /**
     * Creates new form FormularioFuncionarios
     * @param controller Controller da tela
     */
    public FormularioFuncionarios(FormularioFuncionariosController controller) {
        this.controller = controller;
        initComponents();
        jLabelNomeVal.setVisible(false);
        jLabelMatriculaVal.setVisible(false);
        jLabelQualiVal.setVisible(false);
        jLabelDescVal.setVisible(false);
        jLabelCargaVal.setVisible(false);
    }
    
    public void ativarEdicao(Funcionario aEditar) {
        jTextFieldNome.setText(aEditar.getNome());
        jTextFieldMatricula.setText(Long.toString(aEditar.getNumeroMatricula()));
        jTextFieldQuali.setText(aEditar.getQualificacao());
        jTextFieldDesc.setText(aEditar.getDescFuncao());
        jTextFieldCarga.setText(Integer.toString(aEditar.getCargaHoraria()));
        
        this.funcionarioEditado = aEditar;
        this.editando = true;
        
        jLabelCadastrar.setText("Modificar");
        jButtonCadastrar.setText("Confirmar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldQuali = new javax.swing.JTextField();
        jLabelQualificacao = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jLabelFuncao = new javax.swing.JLabel();
        jLabelCarga = new javax.swing.JLabel();
        jTextFieldCarga = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelCadastrar = new javax.swing.JLabel();
        jLabelMatriculaVal = new javax.swing.JLabel();
        jLabelQualiVal = new javax.swing.JLabel();
        jLabelDescVal = new javax.swing.JLabel();
        jLabelCargaVal = new javax.swing.JLabel();
        jLabelNomeVal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabelNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNome.setText("Nome");

        jTextFieldNome.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNome.setToolTipText("Digite seu nome");

        jTextFieldMatricula.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMatricula.setToolTipText("Digite seu telefone");

        jLabelMatricula.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMatricula.setText("Nº de Matrícula");

        jTextFieldQuali.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldQuali.setToolTipText("Digite seu e-mail");

        jLabelQualificacao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelQualificacao.setText("Qualifiação");

        jTextFieldDesc.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDesc.setToolTipText("Digite seu CPF");

        jLabelFuncao.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFuncao.setText("Descrição da Funcão");

        jLabelCarga.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCarga.setText("Carga Horária");

        jTextFieldCarga.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCarga.setToolTipText("Digite seu RG");

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPerformed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelCadastrar.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabelCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastrar.setText("Cadastrar Funcionário");

        jLabelMatriculaVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMatriculaVal.setText("Inválido!");

        jLabelQualiVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelQualiVal.setText("Inválido!");

        jLabelDescVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDescVal.setText("Inválido!");

        jLabelCargaVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelCargaVal.setText("Inválido!");

        jLabelNomeVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNomeVal.setText("Inválido!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldQuali, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMatriculaVal)
                    .addComponent(jLabelQualiVal)
                    .addComponent(jLabelDescVal)
                    .addComponent(jLabelCargaVal)
                    .addComponent(jLabelNomeVal))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabelCadastrar)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNome))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNomeVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelMatricula))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMatriculaVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelQualificacao))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldQuali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelQualiVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelFuncao))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDescVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCargaVal))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCarga)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonCadastrar))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        if(!editando) {
            controller.cadastrarFuncionario(
                jTextFieldNome.getText(),
                jTextFieldMatricula.getText(),
                jTextFieldQuali.getText(),
                jTextFieldDesc.getText(),
                jTextFieldCarga.getText()
            );
        } else {
            controller.modificarFuncionario(funcionarioEditado, 
               jTextFieldNome.getText(),
               jTextFieldMatricula.getText(),
               jTextFieldQuali.getText(),
               jTextFieldDesc.getText(),
               jTextFieldCarga.getText()
            );
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void cancelPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPerformed
        controller.cancelar();
        this.reiniciar();
    }//GEN-LAST:event_cancelPerformed
    
    /**
     * Reinicia os elementos da tela
     */
    public void reiniciar() {
        this.removeAll();
        this.initComponents();
        this.repaint();
        this.revalidate();
        this.editando = false;
        jLabelCadastrar.setText("Cadastrar Funcionário");
        jButtonCadastrar.setText("Cadastrar");
        
        jLabelNomeVal.setVisible(false);
        jLabelMatriculaVal.setVisible(false);
        jLabelQualiVal.setVisible(false);
        jLabelDescVal.setVisible(false);
        jLabelCargaVal.setVisible(false);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelCadastrar;
    private javax.swing.JLabel jLabelCarga;
    private javax.swing.JLabel jLabelCargaVal;
    private javax.swing.JLabel jLabelDescVal;
    private javax.swing.JLabel jLabelFuncao;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelMatriculaVal;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeVal;
    private javax.swing.JLabel jLabelQualiVal;
    private javax.swing.JLabel jLabelQualificacao;
    private javax.swing.JTextField jTextFieldCarga;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldQuali;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabelDescVal() {
        return jLabelDescVal;
    }

    public JLabel getjLabelQualiVal() {
        return jLabelQualiVal;
    }

    public JLabel getjLabelCargaVal() {
        return jLabelCargaVal;
    }

    public JLabel getjLabelMatriculaVal() {
        return jLabelMatriculaVal;
    }
    
    public JLabel getjLabelNomeVal() {
        return jLabelNomeVal;
    }
    
    
}
