package trabalhopoo1.gui.views.veiculos;

import javax.swing.JLabel; 
import trabalhopoo1.entidades.Veiculo;
import trabalhopoo1.gui.controllers.veiculos.FormularioVeiculosController;

public class FormularioVeiculos extends javax.swing.JPanel {
    
    private FormularioVeiculosController controller;
    
    private Veiculo veiculoEditado;
    private boolean editando = false;
    /**
     * Creates new form FormularioVeiculos
     */
    public FormularioVeiculos(FormularioVeiculosController controller) {
        this.controller = controller;
        initComponents();
        jLabelModeloVal.setVisible(false);
        jLabelMarcaVal.setVisible(false);
        jLabelAnoVal.setVisible(false);
        jLabelCorVal.setVisible(false);
        jLabelNMarchasVal.setVisible(false);
        jLabelNPortasVal.setVisible(false);
        jLabelChassiVal.setVisible(false);
    }
    
    public void ativarEdicao(Veiculo aEditar) {
        jTextFieldModelo.setText(aEditar.getModelo());
        jTextFieldMarca.setText(aEditar.getMarca());
        jTextFieldAno.setText(Integer.toString(aEditar.getAno()));
        jTextFieldCor.setText(aEditar.getCor());
        jTextFieldNMarchas.setText(Integer.toString(aEditar.getNumMarchas()));
        jTextFieldNPortas.setText(Integer.toString(aEditar.getNumPortas()));
        jTextFieldChassi.setText(aEditar.getChassi());
        
        this.veiculoEditado = aEditar;
        this.editando = true;
        
        jLabelCadastrar.setText("Modificar");
        jButtonCadastrar.setText("Confirmar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelModelo = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        jTextFieldCor = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jLabelNMarchas = new javax.swing.JLabel();
        jTextFieldNMarchas = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelCadastrar = new javax.swing.JLabel();
        jLabelMarcaVal = new javax.swing.JLabel();
        jLabelAnoVal = new javax.swing.JLabel();
        jLabelCorVal = new javax.swing.JLabel();
        jLabelNMarchasVal = new javax.swing.JLabel();
        jLabelModeloVal = new javax.swing.JLabel();
        jLabelNomeNPortas = new javax.swing.JLabel();
        jTextFieldNPortas = new javax.swing.JTextField();
        jLabelNPortasVal = new javax.swing.JLabel();
        jLabelChassi = new javax.swing.JLabel();
        jTextFieldChassi = new javax.swing.JTextField();
        jLabelChassiVal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabelModelo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelModelo.setText("Modelo");

        jTextFieldModelo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldModelo.setToolTipText("Digite seu nome");

        jTextFieldMarca.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldMarca.setToolTipText("Digite seu telefone");

        jLabelMarca.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMarca.setText("Marca");

        jTextFieldAno.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAno.setToolTipText("Digite seu e-mail");

        jLabelAno.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAno.setText("Ano");

        jTextFieldCor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCor.setToolTipText("Digite seu CPF");

        jLabelCor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCor.setText("Cor");

        jLabelNMarchas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNMarchas.setText("Nº de Marchas");

        jTextFieldNMarchas.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNMarchas.setToolTipText("Digite seu RG");

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPerformed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelCadastrar.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabelCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastrar.setText("Cadastrar Veículo");

        jLabelMarcaVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelMarcaVal.setText("Inválido!");

        jLabelAnoVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelAnoVal.setText("Inválido!");

        jLabelCorVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelCorVal.setText("Inválido!");

        jLabelNMarchasVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNMarchasVal.setText("Inválido!");

        jLabelModeloVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelModeloVal.setText("Inválido!");

        jLabelNomeNPortas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNomeNPortas.setText("Nº de Portas");

        jTextFieldNPortas.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNPortas.setToolTipText("Digite seu nome");

        jLabelNPortasVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNPortasVal.setText("Inválido!");

        jLabelChassi.setForeground(new java.awt.Color(0, 0, 0));
        jLabelChassi.setText("Chassi");

        jTextFieldChassi.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldChassi.setToolTipText("Digite seu nome");

        jLabelChassiVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelChassiVal.setText("Inválido!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNMarchas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelNomeNPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNMarchas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldNPortas, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMarcaVal)
                            .addComponent(jLabelAnoVal)
                            .addComponent(jLabelCorVal)
                            .addComponent(jLabelNMarchasVal)
                            .addComponent(jLabelModeloVal)
                            .addComponent(jLabelNPortasVal)
                            .addComponent(jLabelChassiVal))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabelCadastrar)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelModelo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelModeloVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelMarca))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMarcaVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelAno))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelAnoVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelCor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCorVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNMarchas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNMarchasVal))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNMarchas)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNPortas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNPortasVal))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNomeNPortas)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelChassiVal))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelChassi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        if(!editando) {
            controller.cadastrarVeiculo(
                jTextFieldModelo.getText(),
                jTextFieldMarca.getText(),
                jTextFieldCor.getText(),
                jTextFieldAno.getText(),
                jTextFieldNMarchas.getText(),
                jTextFieldNPortas.getText(),
                jTextFieldChassi.getText()
                );
        } else {
            controller.modificarVeiculo(veiculoEditado, 
               jTextFieldModelo.getText(),
               jTextFieldMarca.getText(),
               jTextFieldCor.getText(),
               jTextFieldAno.getText(),
               jTextFieldNMarchas.getText(),
               jTextFieldNPortas.getText(),
               jTextFieldChassi.getText()
            );
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void cancelPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPerformed
        controller.cancelar();
        this.reiniciar();
    }//GEN-LAST:event_cancelPerformed
    
    /**
     * Reinicia os elementos da tela
     */
    public void reiniciar() {
        this.removeAll();
        this.initComponents();
        this.repaint();
        this.revalidate();
        this.editando = false;
        jLabelCadastrar.setText("Cadastrar Veículo");
        jButtonCadastrar.setText("Cadastrar");
        
        jLabelModeloVal.setVisible(false);
        jLabelMarcaVal.setVisible(false);
        jLabelAnoVal.setVisible(false);
        jLabelCorVal.setVisible(false);
        jLabelNMarchasVal.setVisible(false);
        jLabelNPortasVal.setVisible(false);
        jLabelChassiVal.setVisible(false);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelAnoVal;
    private javax.swing.JLabel jLabelCadastrar;
    private javax.swing.JLabel jLabelChassi;
    private javax.swing.JLabel jLabelChassiVal;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCorVal;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMarcaVal;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelModeloVal;
    private javax.swing.JLabel jLabelNMarchas;
    private javax.swing.JLabel jLabelNMarchasVal;
    private javax.swing.JLabel jLabelNPortasVal;
    private javax.swing.JLabel jLabelNomeNPortas;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldChassi;
    private javax.swing.JTextField jTextFieldCor;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNMarchas;
    private javax.swing.JTextField jTextFieldNPortas;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabelCorVal() {
        return jLabelCorVal;
    }

    public JLabel getjLabelAnoVal() {
        return jLabelAnoVal;
    }

    public JLabel getjLabelNMarchasVal() {
        return jLabelNMarchasVal;
    }

    public JLabel getjLabelMarcaVal() {
        return jLabelMarcaVal;
    }
    
    public JLabel getjLabelModeloVal() {
        return jLabelModeloVal;
    }
    
    public JLabel getjLabelNPortasVal() {
        return jLabelNPortasVal;
    }
    
    public JLabel getjLabelChassiVal() {
        return jLabelChassiVal;
    }
    
    
}
