/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package trabalhopoo1.gui.views;

import javax.swing.JLabel;
import trabalhopoo1.entidades.Cliente;
import trabalhopoo1.gui.controllers.FormularioClientesController;

/**
 *
 * @author vitorbispo
 */
public class FormularioClientes extends javax.swing.JPanel {
    
    private FormularioClientesController controller;
    
    private Cliente clienteEditado;
    private boolean editando = false;
    /**
     * Creates new form FormularioClientes
     */
    public FormularioClientes(FormularioClientesController controller) {
        this.controller = controller;
        initComponents();
        jLabelNomeVal.setVisible(false);
        jLabelTelefoneVal.setVisible(false);
        jLabelEmailVal.setVisible(false);
        jLabelCPFVal.setVisible(false);
        jLabelRGVal.setVisible(false);
    }
    
    public void ativarEdicao(Cliente aEditar) {
        jTextFieldNome.setText(aEditar.getNome());
        jTextFieldTelefone.setText(aEditar.getTelefone());
        jTextFieldEmail.setText(aEditar.getEmail());
        jTextFieldCPF.setText(aEditar.getCpf());
        jTextFieldRG.setText(aEditar.getRg());
        
        this.clienteEditado = aEditar;
        this.editando = true;
        
        jLabelCadastrar.setText("Modificar");
        jButtonCadastrar.setText("Confirmar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jTextFieldRG = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelCadastrar = new javax.swing.JLabel();
        jLabelTelefoneVal = new javax.swing.JLabel();
        jLabelEmailVal = new javax.swing.JLabel();
        jLabelCPFVal = new javax.swing.JLabel();
        jLabelRGVal = new javax.swing.JLabel();
        jLabelNomeVal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 240, 240));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabelNome.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNome.setText("Nome");

        jTextFieldNome.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNome.setToolTipText("Digite seu nome");

        jTextFieldTelefone.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTelefone.setToolTipText("Digite seu telefone");

        jLabelTelefone.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTelefone.setText("Telefone");

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setToolTipText("Digite seu e-mail");

        jLabelEmail.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEmail.setText("E-mail");

        jTextFieldCPF.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCPF.setToolTipText("Digite seu CPF");

        jLabelCPF.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCPF.setText("CPF");

        jLabelRG.setForeground(new java.awt.Color(0, 0, 0));
        jLabelRG.setText("RG");

        jTextFieldRG.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldRG.setToolTipText("Digite seu RG");

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPerformed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelCadastrar.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabelCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastrar.setText("Cadastrar Cliente");

        jLabelTelefoneVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTelefoneVal.setText("Telefone Inválido!");

        jLabelEmailVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelEmailVal.setText("E-mail Inválido!");

        jLabelCPFVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelCPFVal.setText("CPF Inválido!");

        jLabelRGVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelRGVal.setText("RG Inválido!");

        jLabelNomeVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNomeVal.setText("Nome Inválido!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelRG, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelefoneVal)
                            .addComponent(jLabelEmailVal)
                            .addComponent(jLabelCPFVal)
                            .addComponent(jLabelRGVal)
                            .addComponent(jLabelNomeVal))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabelCadastrar)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelNome))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNomeVal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelTelefone))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTelefoneVal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelEmail))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEmailVal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelCPF))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCPFVal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelRG))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRGVal)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        if(!editando) {
            controller.cadastrarCliente(
                jTextFieldNome.getText(),
                jTextFieldTelefone.getText(),
                jTextFieldEmail.getText(),
                jTextFieldCPF.getText(),
                jTextFieldRG.getText()
            );
        } else {
            controller.modificarCliente(clienteEditado, 
                jTextFieldNome.getText(),
                jTextFieldTelefone.getText(),
                jTextFieldEmail.getText(),
                jTextFieldCPF.getText(),
                jTextFieldRG.getText()
            );
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void cancelPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPerformed
        controller.cancelar();
        this.reiniciar();
    }//GEN-LAST:event_cancelPerformed
    
    public void reiniciar() {
        this.removeAll();
        this.initComponents();
        this.repaint();
        this.revalidate();
        this.editando = false;
        jLabelCadastrar.setText("Cadastrar Cliente");
        jButtonCadastrar.setText("Cadastrar");
        
        jLabelNomeVal.setVisible(false);
        jLabelTelefoneVal.setVisible(false);
        jLabelEmailVal.setVisible(false);
        jLabelCPFVal.setVisible(false);
        jLabelRGVal.setVisible(false);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCPFVal;
    private javax.swing.JLabel jLabelCadastrar;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailVal;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeVal;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelRGVal;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTelefoneVal;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRG;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabelCPFVal() {
        return jLabelCPFVal;
    }

    public JLabel getjLabelEmailVal() {
        return jLabelEmailVal;
    }

    public JLabel getjLabelRGVal() {
        return jLabelRGVal;
    }

    public JLabel getjLabelTelefoneVal() {
        return jLabelTelefoneVal;
    }
    
    public JLabel getjLabelNomeVal() {
        return jLabelNomeVal;
    }
    
    
}
