package trabalhopoo1.gui.views.vendas;

import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JLabel; 
import javax.swing.JTextField;
import trabalhopoo1.entidades.Venda;
import trabalhopoo1.gui.controllers.vendas.FormularioVendasController;

public class FormularioVendas extends javax.swing.JPanel {
    
    private FormularioVendasController controller;
    
    private Venda vendaEditada;
    private boolean editando = false;
    /**
     * Creates new form FormularioVendas
     */
    public FormularioVendas(FormularioVendasController controller) {
        this.controller = controller;
        initComponents();
        jLabelClienteVal.setVisible(false);
        jLabelFuncionarioVal.setVisible(false);
        jLabelVeiculoVal.setVisible(false);
        jLabelDataVal.setVisible(false);
        jLabelValorVal.setVisible(false);
    }
    
    public void ativarEdicao(Venda aEditar) {
        jTextFieldCliente.setText(aEditar.getCliente().getCpf());
        jTextFieldFuncionario.setText(Long.toString(aEditar.getFuncionario().getNumeroMatricula()));
        jTextFieldVeiculo.setText(aEditar.getVeiculo().getChassi());
        jTextFieldData.setText(aEditar.getData().toString());
        jTextFieldValor.setText(Double.toString(aEditar.getValor()));
        
        this.vendaEditada = aEditar;
        this.editando = true;
        
        jLabelCadastrar.setText("Modificar");
        jButtonCadastrar.setText("Confirmar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabelModelo = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jTextFieldFuncionario = new javax.swing.JTextField();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldVeiculo = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        jTextFieldData = new javax.swing.JTextField();
        jLabelCor = new javax.swing.JLabel();
        jLabelNMarchas = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jLabelCadastrar = new javax.swing.JLabel();
        jLabelDataVal = new javax.swing.JLabel();
        jLabelValorVal = new javax.swing.JLabel();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jComboBoxFuncionarios = new javax.swing.JComboBox<>();
        jComboBoxVeiculos = new javax.swing.JComboBox<>();
        jLabelClienteVal = new javax.swing.JLabel();
        jLabelFuncionarioVal = new javax.swing.JLabel();
        jLabelVeiculoVal = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setBackground(new java.awt.Color(240, 240, 240));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabelModelo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelModelo.setText("Cliente (CPF)");

        jTextFieldCliente.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCliente.setToolTipText("Digite seu nome");

        jTextFieldFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFuncionario.setToolTipText("Digite seu telefone");

        jLabelMarca.setForeground(new java.awt.Color(0, 0, 0));
        jLabelMarca.setText("Funcionário (Nº Matrícula)");

        jTextFieldVeiculo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldVeiculo.setToolTipText("Digite seu e-mail");

        jLabelAno.setForeground(new java.awt.Color(0, 0, 0));
        jLabelAno.setText("Veículo (Chassi)");

        jTextFieldData.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldData.setToolTipText("Digite seu CPF");

        jLabelCor.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCor.setText("Data");

        jLabelNMarchas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNMarchas.setText("Valor");

        jTextFieldValor.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldValor.setToolTipText("Digite seu RG");

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPerformed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(204, 204, 255));
        jButtonCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jLabelCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        jLabelCadastrar.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabelCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadastrar.setText("Cadastrar Venda");

        jLabelDataVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDataVal.setText("Inválido!");

        jLabelValorVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelValorVal.setText("Inválido!");

        jComboBoxClientes.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxClientes.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxClientes.setMaximumRowCount(5);
        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7" }));
        jComboBoxClientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxClientesItemStateChanged(evt);
            }
        });
        jComboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientesActionPerformed(evt);
            }
        });

        jComboBoxFuncionarios.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxFuncionarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFuncionarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFuncionariosItemStateChanged(evt);
            }
        });

        jComboBoxVeiculos.setBackground(new java.awt.Color(240, 240, 240));
        jComboBoxVeiculos.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxVeiculos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxVeiculos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxVeiculosItemStateChanged(evt);
            }
        });

        jLabelClienteVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelClienteVal.setText("Inválido!");

        jLabelFuncionarioVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelFuncionarioVal.setText("Inválido!");

        jLabelVeiculoVal.setForeground(new java.awt.Color(255, 0, 51));
        jLabelVeiculoVal.setText("Inválido!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelAno, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelNMarchas, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                                    .addComponent(jLabelMarca))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataVal)
                            .addComponent(jLabelValorVal)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxVeiculos, 0, 143, Short.MAX_VALUE)
                                    .addComponent(jComboBoxFuncionarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelClienteVal)
                                        .addComponent(jLabelFuncionarioVal, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabelVeiculoVal, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabelCadastrar)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelModelo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelClienteVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelMarca))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelFuncionarioVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelAno))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelVeiculoVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelCor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDataVal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelValorVal))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNMarchas)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(83, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        if(!editando) {
            controller.cadastrarVenda(
                jTextFieldCliente.getText(),
                jTextFieldFuncionario.getText(),
                jTextFieldVeiculo.getText(),
                jTextFieldData.getText(),
                jTextFieldValor.getText()
                );
        } else {
            controller.modificarVenda(vendaEditada, 
               jTextFieldCliente.getText(),
               jTextFieldFuncionario.getText(),
               jTextFieldVeiculo.getText(),
               jTextFieldData.getText(),
               jTextFieldValor.getText()
            );
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void cancelPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPerformed
        controller.cancelar();
        this.reiniciar();
    }//GEN-LAST:event_cancelPerformed

    private void jComboBoxClientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxClientesItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
            controller.selecionarCliente(jComboBoxClientes.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxClientesItemStateChanged

    private void jComboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClientesActionPerformed

    private void jComboBoxFuncionariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFuncionariosItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
            controller.selecionarFuncionario(jComboBoxFuncionarios.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxFuncionariosItemStateChanged

    private void jComboBoxVeiculosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxVeiculosItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED)
            controller.selecionarVeiculo(jComboBoxVeiculos.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxVeiculosItemStateChanged
    
    /**
     * Reinicia os elementos da tela
     */
    public void reiniciar() {
        this.removeAll();
        this.initComponents();
        this.repaint();
        this.revalidate();
        this.editando = false;
        jLabelCadastrar.setText("Cadastrar Veículo");
        jButtonCadastrar.setText("Cadastrar");
        
        jLabelClienteVal.setVisible(false);
        jLabelFuncionarioVal.setVisible(false);
        jLabelVeiculoVal.setVisible(false);
        jLabelDataVal.setVisible(false);
        jLabelValorVal.setVisible(false);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox<String> jComboBoxClientes;
    private javax.swing.JComboBox<String> jComboBoxFuncionarios;
    private javax.swing.JComboBox<String> jComboBoxVeiculos;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCadastrar;
    private javax.swing.JLabel jLabelClienteVal;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelDataVal;
    private javax.swing.JLabel jLabelFuncionarioVal;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNMarchas;
    private javax.swing.JLabel jLabelValorVal;
    private javax.swing.JLabel jLabelVeiculoVal;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldFuncionario;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldVeiculo;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabelDataVal() {
        return jLabelDataVal;
    }

    public JLabel getjLabelClienteVal() {
        return jLabelClienteVal;
    }

    public JLabel getjLabelValorVal() {
        return jLabelValorVal;
    }

    public JLabel getjLabelFuncionarioVal() {
        return jLabelFuncionarioVal;
    }
    
    public JLabel getjLabelVeiculoVal() {
        return jLabelVeiculoVal;
    }

    public JComboBox<String> getjComboBoxClientes() {
        return jComboBoxClientes;
    }

    public JComboBox<String> getjComboBoxFuncionarios() {
        return jComboBoxFuncionarios;
    }

    public JComboBox<String> getjComboBoxVeiculos() {
        return jComboBoxVeiculos;
    }

    public JTextField getjTextFieldCliente() {
        return jTextFieldCliente;
    }

    public void setjTextFieldCliente(JTextField jTextFieldCliente) {
        this.jTextFieldCliente = jTextFieldCliente;
    }

    public JTextField getjTextFieldFuncionario() {
        return jTextFieldFuncionario;
    }

    public void setjTextFieldFuncionario(JTextField jTextFieldFuncionario) {
        this.jTextFieldFuncionario = jTextFieldFuncionario;
    }

    public JTextField getjTextFieldVeiculo() {
        return jTextFieldVeiculo;
    }

    public void setjTextFieldVeiculo(JTextField jTextFieldVeiculo) {
        this.jTextFieldVeiculo = jTextFieldVeiculo;
    }
    
    
}
